# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7438f35335a2f64fce821e54a5175a9815b201a5f91318729bfd3b4f24cb985a64282d043da7ab4135f9b67e3c3ff6d726c934be0a1b9db441c9c2b28746ad5b

test:
  secret_key_base: 8bc3d0d61b429b6fe8a7a9cfc650b122921546b54e847dc27dcf2360a2de5f70292b6cd28b81797d957f1aed94739b58ac621dd8f112cca4a54bfd672568e2d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
